site_name: Cheep Learning

theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light green
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light green
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: overrides

google_analytics:
  - G-8JSVH7S4KX
  - auto

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - fontawesome_markdown
  - def_list
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list

extra_javascript:
  - js/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

extra:
  font:
    text: "Noto Sans JP"
    code: "Monaco"
  search:
    language: "jp"
